caparol_center_spb/caparol_center_spb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('services', include('services.urls', namespace='services')),
]

caparol_center_spb/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.main_render, name='main_render'),
    path('question', views.question, name='question')
]

caparol_center_spb/services/urls.py
from django.urls import path
from . import views

app_name = 'services'

urlpatterns = [
    path('', views.services_render, name='services_render'),
]

caparol_center_spb/main/models.py
from django.db import models


class Question(models.Model):
    email = models.EmailField()
    initial = models.CharField(max_length=50)
    question = models.CharField(max_length=500)

    def __str__(self):
        return self.initial

caparol_center_spb/services/models.py
from django.db import models

class Protect(models.Model):
    img = models.FileField()
    description = models.CharField(max_length=500)
    title = models.CharField(max_length=50)

class Cover(models.Model):
    img = models.FileField()
    title = models.CharField(max_length=50)
    description = models.CharField(max_length=500)
    price = models.DecimalField(decimal_places=0,max_digits=7)
    protect = models.ForeignKey(Protect, on_delete=models.CASCADE)

caparol_center_spb/main/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Question
from django.contrib import messages

def main_render(request):
    return render(request, 'main/index.html')

def question(request):
    if request.method == 'POST':
        email = request.POST.get("email")
        initial = request.POST.get("initial")
        question = request.POST.get("question")


        Question.objects.create(email=email,
                                initial=initial,
                                question=question)

        messages.info(request,initial + ", ваш вопрос успешно отправлен!")

    return HttpResponseRedirect(reverse('main:main_render'))

caparol_center_spb/services/views.py
from django.shortcuts import render
from .models import Protect, Cover

def services_render(request):
    protects = Protect.objects.all()
    covers = Cover.objects.all()
    return render(request, "services/services.html", {'protects': protects, 'covers': covers})

caparol_center_spb/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8"> {% load static%}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %} {% endblock title %}</title>
</head>

<body>
    <a name="yakor-top"></a>
    <header class="header-section">
        <div class="header container">
            <a href=""><img src="{% static 'img/Logo.jpg' %}" alt="Логотип" class="logo"></a>
            <nav class="header-nav">
                <ul class="main-list">
                    <li class="main-list__items"><a href="#">Главная</a></li>
                    <li class="main-list__items"><a href="{% url 'services:services_render' %}">Готовые решения</a></li>
                    <li class="main-list__items"><a href="#">Шоу-Рум</a></li>
                    <li class="main-list__items"><a href="#">Контакты</a></li>
                </ul>
            </nav>
        </div>
    </header>
    {% block content %}{% endblock content %}
    <footer>
        <div class="footer container">
            <div class="map">
                <iframe src="https://yandex.ru/map-widget/v1/?um=constructor%3A3a1d8625607f6df773281a3df4d10e638b7112752219650d56e826c03ada278a&amp;source=constructor" width="100%" height="400" frameborder="0"></iframe>
            </div>
            <div class="footer-bottom">
                <p>© 2019 Caparol Center SPB</p>
                <nav class="footer-menu">
                    <ul class="menu">
                        <li class="footer-menu__item">
                            <a href="#" class="footer-menu__link">Все товары</a>
                        </li>
                        <li class="footer-menu__item">
                            <a href="#" class="footer-menu__link">Шоу-Рум</a>
                        </li>
                    </ul>
                </nav>
                <a href="#yakor-top" class="footer-menu__link">Наверх</a>
            </div>
        </div>
    </footer>
</body>

</html>

caparol_center_spb/templates/main/index.html
{% extends "base.html" %} {% block title %} Caparol Center SPB {% endblock title %} {% block content %}
<section class="section-first">
    <div class="container container-first">
        <div class="section-first__content">
            <h1>Caparol Center SPB</h1>
            <p>Место, где делаются шедевры декоративной мысли. Здесь дизайнер со своим клиентом в непринужденной обстановке могут обсудить проект и протестировать в реальном времени.</p>
            <a href="#" class="btn">Шоу-Рум</a>
        </div>
    </div>
</section>
<section class="section-second">
    <div class="container container-second">
        <div class="section-second__content">
            <div class="section-second__info">
                <h2>О шоу-руме</h2>
                <p>Мы официальный дистрибьютер немецкого бренда caparol, являющегося наиболее известным, востребованным и авторитетным брендом в своей отрасли. Наш ассортимент включает в себя несколько товарных линеек и множество товаров.</p>
            </div>
            <div class="section-second__gallery">
                <img src="/static/img/Showroom_1.jpg" alt="" class="section-second__images">
                <img src="/static/img/Showroom_2.jpg" alt="" class="section-second__images">
                <img src="/static/img/Showroom_3.jpg" alt="" class="section-second__images">
            </div>
        </div>
    </div>
</section>
<section class="section-third">
    <div class="container container-third">
        <div class="section-third__left-side">
            <div class="container-third__block">
                <div class="block__left-side">
                    <img src="/static/img/Block-client.png" alt="">
                </div>
                <div class="block__rigth-side">
                    <h3>
                        Клиенту
                    </h3>
                    <p>Enim justo facilisi justo magnis dolor curabitur. Ornare diam dictumst amet mauris. Mollis nisi, eget dignissim sollicitudin.</p>
                </div>
            </div>
        </div>
        <div class="section-third__right-side">
            <div class="container-third__block">
                <div class="block__top-side">
                    <h3>Дизайнеру</h3>
                    <img src="/static/img/Block-designer.png" alt="">
                </div>
                <div class="block__bottom-side">
                    <p>Ornare diam dictumst amet mauris. Mollis nisi, eget dignissim sollicitudin.</p>
                </div>
            </div>
            <div class="container-third__block">
                <div class="block__top-side">
                    <h3>Архитектору</h3>
                    <img src="/static/img/Block-architecher.png" alt="">
                </div>
                <div class="block__bottom-side">
                    <p>Ornare diam dictumst amet mauris. Mollis nisi, eget dignissim sollicitudin.</p>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="section-fourth">
    <div class="container container-fourth">
        <div class="section-fourth__content">
            <h2>Почему мы?</h2>
            <div class="section-fourth__block">
                <div class="section-fourth__items">
                    <div class="items__top">
                        <img src="/static/img/Card_1.svg" alt="Аналитика">
                        <h3>Аналитика</h3>
                    </div>
                    <p>Мы можем оценить возможности проекта, экономический статус и подобрать для вас уникальное предложение.</p>
                </div>
                <div class="section-fourth__items">
                    <div class="items__top">
                        <img src="static/img/Card_2.svg" alt="Встреча с клиентами">
                        <h3>Встреча с клиентами</h3>
                    </div>
                    <p>Мы готовы предоставить вам место для встреч с вашим клиентом.</p>
                </div>
                <div class="section-fourth__items">
                    <div class="items__top">
                        <img src="static/img/Card_3.svg" alt="Консультация">
                        <h3>Консультация</h3>
                    </div>
                    <p>Мы готовы с радостью оказать консультацию, а так-же провести мастер-класс.</p>
                </div>
                <div class="section-fourth__items">
                    <div class="items__top">
                        <img src="static/img/Card_4.svg" alt="Знакомый бренд">
                        <h3>Знакомый бренд</h3>
                    </div>
                    <p>Мы являемся официальным дистрибьютером компании DAW SE, поставлющую продукцию caparol в РФ.</p>
                </div>
            </div>
        </div>
</section>
<section class="section-fifth">
    <div class="containter container-fifth">
        <div class="slider">
            <div class="slide slide-1" active>
                <div class="side-left">
                    <img src="/static/img/Slider_img.jpg" alt="" class="img-slider">
                    <div class="colors"></div>
                </div>
                <div class="side-right">
                    <h3>Ameloft</h3>
                    <ul class="list">
                        <li class="list__item">
                            <img src="/static/img/Slider-check.png" alt="">
                            <p>afafsfgs</p>
                        </li>
                        <li class="list__item">
                            <img src="/static/img/Slider-check.png" alt="">
                            <p>fsgsgf</p>
                        </li>
                        <li class="list__item">
                            <img src="/static/img/Slider-check.png" alt="">
                            <p>hghfhh</p>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="slide slide-2">
                <div class="side-left">
                    <img src="/static/img/Slider_img.jpg" alt="" class="img-slider">
                    <div class="colors"></div>
                </div>
                <div class="side-right">
                    <h3>Ameloft</h3>
                    <ul class="list">
                        <li class="list__item">
                            <img src="/static/img/Slider-check.png" alt="">
                            <p>afafsfgs</p>
                        </li>
                        <li class="list__item">
                            <img src="/static/img/Slider-check.png" alt="">
                            <p>fsgsgf</p>
                        </li>
                        <li class="list__item">
                            <img src="/static/img/Slider-check.png" alt="">
                            <p>hghfhh</p>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="slide slide-3">
                <div class="side-left">
                    <img src="/static/img/Slider_img.jpg" alt="" class="img-slider">
                    <div class="colors"></div>
                </div>
                <div class="side-right">
                    <h3>Ameloft</h3>
                    <ul class="list">
                        <li class="list__item">
                            <img src="/static/img/Slider-check.png" alt="">
                            <p>afafsfgs</p>
                        </li>
                        <li class="list__item">
                            <img src="/static/img/Slider-check.png" alt="">
                            <p>fsgsgf</p>
                        </li>
                        <li class="list__item">
                            <img src="/static/img/Slider-check.png" alt="">
                            <p>hghfhh</p>
                        </li>
                    </ul>
                </div>

            </div>
        </div>
        <div class="slider-arrows">
            <img src="/static/img/Arrow-left.png" alt="" class="arrow" id="arrow_left">
            <img src="/static/img/Arrow-right.png" alt="" class="arrow" id="arrow_right">
        </div>
    </div>
</section>
<section class="section-form">
    <div class="container container-form">
        <div class="left-side">
            <h3>Что выбрать</h3>
            <p>Напишите нам и мы поможет подобрать необходимые материалы.</p>
        </div>
        <form action="{% url 'main:question' %}" method="POST" class="main-form">
            {% csrf_token %}

            <input type="email" placeholder="Ваш email" class="field field-input" name="email">
            <input type="name" placeholder="Ваше имя и отчество" class="field field-input" name="initial">
            <textarea id="" cols="30" rows="10" placeholder="Ваш вопрос" class="field field-textarea" name="question"></textarea>
            <button type='submit' class="field form-btn">Отправить</button>
        </form>

        {% if messages %} {% for message in messages %}
        <script>
            alert('{{ message }}')
        </script>
        {% endfor %} {% endif %}

    </div>
</section>


<script src="/static/js/main.js"></script>
{% endblock content %}

caparol_center_spb/templates/main/ready-decision.html
{% extends "base.html" %} {% block title %} Caparol Center SPB {% endblock title %} {% block content %}
<div class="container container-decision">
    <h1>Готовые решения</h1>
    <div class="decision-top">
        <h2>Шаг 1 <span>Выберите защиту фасада</span></h2>
        <div class="decision-images">
            <div class="card">
                <img src="/static/img/Decision-card_1.jpg" alt="">
                <p>Вероятно, лучшая теплоизоляция фасадов в мире!</p>
            </div>
            <div class="card">
                <img src="/static/img/Decision-card_2.jpg" alt="">
                <p>Capatect LONGLIFE</p>
            </div>
            <div class="card">
                <img src="/static/img/Decision-card_3.jpg" alt="">
                <p>Лучшая система в сегменте «Стандарт»</p>
            </div>
        </div>
    </div>
    <div class="decision-middle">
        <h2>Шаг 2 <span>Доступные для него покрытия</span></h2>
        <div class="decision-images">
            <img src="/static/img/Desicion_1.jpg" alt="">
            <img src="/static/img/Desicion_2.jpg" alt="">
            <img src="/static/img/Desicion_3.jpg" alt="">
            <img src="/static/img/Desicion_4.jpg" alt="">
        </div>
    </div>
    <div class="decision-bottom">
        <div class="left-side">
            <img src="/static/img/Desicion_1.jpg" alt="">
            <div class="colors"></div>
        </div>
        <div class="right-side">
            <h3>Zima Blue</h3>
            <div class="description">

            </div>
            <div class="extra-info">
                <button class="btn btn_extra-info"></button>
                <p class="extra-info__price"></p>
            </div>

        </div>
    </div>
</div>
{% endblock content %}

caparol_center_spb/templates/services/services.html
{% extends "base.html" %} {% block title %} Caparol Center SPB {% endblock title %} {% block content %}
<div class="container container-decision">
    <h1>Готовые решения</h1>
    <div class="decision-top">
        <h2>Шаг 1 <span>Выберите защиту фасада</span></h2>
        {% for protect in protects %}
            <div class="card card_decision">
                <img class="card-img" src=" {{ protect.img.url }} " alt=" {{ protect.title }} ">
                <p>{{ protect.description }}</p>
            </div>
        {% endfor %}
        <div class="decision-images">
            <div class="card card_decision" id="card_decision-1">
                <img class="card-img" id="card-img-1" src="/static/img/Decision-card_1.svg" alt="">
                <p>Вероятно, лучшая теплоизоляция фасадов в мире!</p>
            </div>
            <div class="card card_decision" id="card_decision-2">
                <img class="card-img" id="card-img-2" src="/static/img/Decision-card_2.svg" alt="">
                <p>Capatect LONGLIFE</p>
            </div>
            <div class="card card_decision" id="card_decision-3">
                <img class="card-img" id="card-img-3" src="/static/img/Decision-card_3.svg" alt="">
                <p>Лучшая система в сегменте «Стандарт»</p>
            </div>
        </div>
    </div>
    <div class="decision-middle">
        <h2>Шаг 2 <span>Доступные для него покрытия</span></h2>
        
        
            
        <div class="decision-images">
            {% for cover in covers %}
                <img src=" {{ cover.img.url }} " alt="">
            {% endfor %}
            <img src="/static/img/Desicion_1.svg" alt="">
            <img src="/static/img/Desicion_2.svg" alt="">
            <img src="/static/img/Desicion_3.svg" alt="">
            <img src="/static/img/Desicion_4.svg" alt="">
        </div>
    </div>
    <div class="decision-bottom">
        <div class="left-side">
            <img src="/static/img/Desicion_1.svg" alt="">
            <div class="colors"></div>
        </div>
        <div class="right-side">
            <h3>Zima Blue</h3>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Velit metus blandit eu nunc, eu sit erat aenean. Adipiscing ullamcorper felis neque mauris eu lacus. Accumsan.
            </p>
            <div class="extra-info">
                <a href="#">Подробнее</a>
                <p>Цена: 17000р</p>
            </div>

        </div>
    </div>
</div>
<script src="/static/js/services.js"></script>
{% endblock content %}